export const inputs = [
  {
    key: "company",
    label: "Azienda",
    type: "select",
    options: ["Apophis_Contacts", "Digital_Center"],
  },
  {
    key: "invoiceNum",
    label: "Numero fattura",
    placeholder: "Inserisci numero",
    inputType: "text",
    type: "input",
  },
  {
    key: "date",
    label: "Data compilazione",
    placeholder: "Seleziona data",
    inputType: "date",
    type: "input",
  },
  {
    key: "currentMonth",
    label: "Mese di riferimento",
    type: "select",
    options: [
      "Gennaio",
      "Febbraio",
      "Marzo",
      "Aprile",
      "Maggio",
      "Giugno",
      "Luglio",
      "Agosto",
      "Settembre",
      "Ottobre",
      "Novembre",
      "Dicembre",
    ],
  },
  {
    key: "netAmount",
    label: "Compenso netto",
    placeholder: "Inserisci compenso",
    inputType: "number",
    type: "input",
  },
];
